use_frameworks!

target 'AIASwiftFramework_Example' do
  pod 'AIASwiftFramework', :path => '../'

  target 'AIASwiftFramework_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
